---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: Clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from $(workspaces.source.path) ..."
        if [ -d "$(workspaces.source.path)" ]; then
          rm -rf "$(workspaces.source.path)"/*
          rm -rf "$(workspaces.source.path)"/.[!.]*
          rm -rf "$(workspaces.source.path)"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  description: Run flake8 lint check on Python code.
  params:
    - name: args
      description: Arguments to pass to flake8
      type: string
      default: "--count --max-complexity=10 --max-line-length=127"
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        python -m pip install --upgrade pip
        python -m pip install flake8
        flake8 . $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
          #!/bin/bash
          set -e
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          nosetests $(params.args)
